
/**************************************************************
 *	
 *	battleLoop, 8 bit, 44100Hz,
 *	1 channel, 352449 bytes/channel
 *	Total Size: 1 * 352449 + 4 (header) = 352493 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Philip\Desktop\SoundLab+-+complete\wav2c\battleLoop.wav
 *	Time-stamp: Sun Dec 05 22:37:36 2010
 *	
 **************************************************************/

#ifndef __BATTLELOOPH__
#define __BATTLELOOPH__

#define BATTLELOOPFREQ 44100
#define BATTLELOOPLEN 352449

extern const unsigned char battleLoop[352449];

#endif /* __BATTLELOOPH__ */
