
/**************************************************************
 *	
 *	shootNoise, 8 bit, 11025Hz,
 *	1 channel, 3660 bytes/channel
 *	Total Size: 1 * 3660 + 4 (header) = 3704 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Philip\Desktop\SoundLab+-+complete\wav2c\shootNoise.wav
 *	Time-stamp: Sun Dec 05 22:44:23 2010
 *	
 **************************************************************/

#ifndef __SHOOTNOISEH__
#define __SHOOTNOISEH__

#define SHOOTNOISEFREQ 11025
#define SHOOTNOISELEN 3660

extern const unsigned char shootNoise[3660];

#endif /* __SHOOTNOISEH__ */
