
/**************************************************************
 *	
 *	soundLoop, 8 bit, 11025Hz,
 *	1 channel, 220500 bytes/channel
 *	Total Size: 1 * 220500 + 4 (header) = 220544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Philip\Desktop\SoundLab+-+complete\wav2c\soundLoop.wav
 *	Time-stamp: Sun Dec 05 21:45:02 2010
 *	
 **************************************************************/

#ifndef __SOUNDLOOPH__
#define __SOUNDLOOPH__

#define SOUNDLOOPFREQ 11025
#define SOUNDLOOPLEN 220500

extern const unsigned char soundLoop[220500];

#endif /* __SOUNDLOOPH__ */
